
scope streamer
{
    alias Traffic = Bytes;

    interface Channel
    {
        in flow:    (Traffic);
        in reset:   ();

        out flow:   (Traffic);
        out reset:  ();
    }


    interface Hub
    {
        in channel: () -> (Channel);
        in reset:   ();

alias interface = int8;
alias iid = int8;

        in put:     (interface);
        out put:    (interface);

        in get:     (iid) -> (interface);
        out get:    (iid) -> (interface);

        in join:    (Channel);
    }

}
