

//temporary
alias Data = list<uint8>;


scope net
{
    /////////////////////////////////////////////////////////
    iface Host
    {
        in interfaces:          ()              -> list<Interface>;

        out interfaceAdded:     (Interface v);
        out interfaceRemoved:   (Interface v);

        in ip4StreamHost:       ()              -> ip4::stream::Host;
        in ip4DatagramHost:     ()              -> ip4::datagram::Host;

        in ip6StreamHost:       ()              -> ip6::stream::Host;
        in ip6DatagramHost:     ()              -> ip6::datagram::Host;

        in localStreamHost:     ()              -> local::stream::Host;
    }

    /////////////////////////////////////////////////////////
    iface Interface
    {
        in flags:           () -> uint32;
        out flagsChanged:   ();

        in mtu:             () -> uint32;
        out mtuChanged:     ();

        in name:            () -> string;
        out nameChanged:    ();
        
        in ip4Nets:         () -> list<ip4::Net>;
        out ip4NetsChanged: ();
        
        in ip6Nets:         () -> list<ip6::Net>;
        out ip6NetsChanged: ();
    }

    /////////////////////////////////////////////////////////
    scope ip4
    {
        struct Ip
        {
            array<uint8, 4> octets;
        }
        
        struct Address: Ip
        {
            uint16 port;
        }

        struct Net
        {
            Ip address;
            Ip netmask;
            Ip broadcast;
        } 

        include "net/stream.inc";
        include "net/datagram.inc";
    }

    /////////////////////////////////////////////////////////
    scope ip6
    {
        struct Ip
        {
            array<uint8, 16> octets;
        }
        
        struct Address: Ip
        {
            uint16 port;
        }

        struct Net
        {
            Ip address;
            uint16 prefixLength;
            uint32 scopeId;
        }
        
        include "net/stream.inc";
        include "net/datagram.inc";
    }

    /////////////////////////////////////////////////////////
    scope local
    {
        struct Address
        {
            string key;
        }

        include "net/stream.inc";
    }
}
