

//temporary
alias Data = list<uint8>;


scope net
{
    /////////////////////////////////////////////////////////
    iface Host
    {
        out list<Interface> interfaces();
        in nowait void interfaceAdded(Interface v);
        in nowait void interfaceRemoved(Interface v);

        out ip4::stream::Host ip4StreamHost();
        out ip4::datagram::Host ip4DatagramHost();

        out ip6::stream::Host ip6StreamHost();
        out ip6::datagram::Host ip6DatagramHost();

        out local::stream::Host localStreamHost();
    }

    /////////////////////////////////////////////////////////
    iface Interface
    {
        out uint32 flags();
        in nowait void flagsChanged();

        out uint32 mtu();
        in nowait void mtuChanged();

        out string name();
        in nowait void nameChanged();
        
        out list<ip4::Net> ip4Nets();
        in nowait void ip4NetsChanged();
        
        out list<ip6::Net> ip6Nets();
        in nowait void ip6NetsChanged();
    }

    /////////////////////////////////////////////////////////
    scope ip4
    {
        struct Ip
        {
            array<uint8, 4> octets;
        }
        
        struct Address: Ip
        {
            uint16 port;
        }

        struct Net
        {
            Ip address;
            Ip netmask;
            Ip broadcast;
        } 

        include "net/stream.inc";
        include "net/datagram.inc";
    }

    /////////////////////////////////////////////////////////
    scope ip6
    {
        struct Ip
        {
            array<uint8, 16> octets;
        }
        
        struct Address: Ip
        {
            uint16 port;
        }

        struct Net
        {
            Ip address;
            uint16 prefixLength;
            uint32 scopeId;
        }
        
        include "net/stream.inc";
        include "net/datagram.inc";
    }

    /////////////////////////////////////////////////////////
    scope local
    {
        struct Address
        {
            string key;
        }

        include "net/stream.inc";
    }
}
